### PR TITLE
Change many style

### PR DESCRIPTION
**Pull request by muhibbudins**
Hi @eduardsi ,

Thanks for awesome project, on my first *pull request* i made some change at many .vue file. With in create entire video clickable (ref #12 ) and then try to restructure .vue file to standard style code (soon maybe we can use eslint 👍).

Change log :

- Fix card height and restructure scss code at VideoCard
- Change some code structure at .vue file
- Make entire video clickable ref #12 

Thank you

### CODE REVIEW

**Comment by aadamovich** [comment]
@eduardsi ^

**Comment by eduardsi** [comment]
Hey @muhibbudins!

Thanks for this. Can you elaborate why .flex layout? When .flex, I am observing issue with horizontal alignment on small devices: https://cl.ly/0j1l0U2A2G0K

**Comment by muhibbudins** [comment]
Hi @eduardsi ,

Upss i forgot about this to test on small device. I think we can use min-height to solve this, i'll push latest code as soon as possible.

Thanks

**Comment by eduardsi** [comment]
Hey @muhibbudins 

Thanks! Quick question before we dive into the code  – what we are trying to solve with .flex layout? : )

**Comment by muhibbudins** [comment]
Hi @eduardsi ,

I feel wrong about that, yesterday i think .flex on bulma can work in mobile too. I use .flex to make VideoCard have the same height, because i see VideoCard with different height quite disturbing.

Thanks

**Comment by eduardsi** [comment]
Hey Muhibbudin

Thanks for the clear problem explanation – now I understand what's wrong with video heights.

Solved the issue here, inspired by your solution: https://github.com/watch-devtube/web/commit/3fda7777db106009ed4f2c81c4c15273dbe2f7ce

Videos won't be clickable, but images now are.

I am closing this PR, as there is no added functionality anymore. Large code reformatting merges will be postponed until the following issue is resolved: https://github.com/watch-devtube/web/issues/40. 

Thank for contributing, bro!

**Comment by muhibbudins** [comment]
Hi @eduardsi,

You're welcome, i hope i can contribute for another issue or design.

**Pull request closed without merging**
