### PR TITLE
Styles improved

### PR DESCRIPTION
**Pull request by MeikelLP**
## What?

* Moved styles too sass files and import them.
* Replaced cookies with local storage.
* Removed server side conditional rendering.

### Update

* Fixed the footer
* Additionally I extracted the css to be in an individual file (improved caching).
* Fixed theme not applying when not logged in (theme component always visible)
* Fixed some minor issues with css selector: `html html` (see `_fixes.sass`)
* Fixed some changes in bulma 0.74 -> 0.75 (probably)

### Why SASS?

IMO sass (or scss) is better for developing. I explicitly included `Bulma` & `Bulmaswatch`. For now this causes the app to include both night and day theme (which will increase the app size). This can be used to overwrite Bulma variables to colorize Bulma freely without overwriting every rule where color-x applies. With this bulmaswatch could later be replaced with a simple variable-overwrite-file (like bulmaswatch does internally).

### Why `html.theme-night` & `html.theme-day`?

Currently I don't know a way a good way to dynamically reference a css file inside a Vue.js app (fully clientside). That's why I decided to modify the class of the root html (some additional classes required for bulmaswatch). You usually don't do this in HTML but this is can be improved in the future.

With some webpack magic it's probably possible that these 2 sass theme files could be extracted and instead of setting the HTML tag class to `theme-night` and `theme-day` an individual file could be referenced. This would decrease the load time of the app.

### Why no cookies?

IMO this is a fully client side preference which the server should not know about (it's just colors). So I decided to remove cookies and replace them with `localStorage`. This also "improves" the server side performance (probably like 1ns)

### CODE REVIEW

**Comment by sizovs** [comment]
Thanks for contributing this. The change has broken the layout:

* Footer is now in the middle of the page
* Video titles overflow 

image

**Comment by MeikelLP** [comment]
Thank you I'll look into it. I did some minor "improvements" as I thought.

**Comment by MeikelLP** [comment]
I fixed the footer.
I don't know if I fixed the overflow as I cannot reproduce this view (no videos :( )...

**Comment by sizovs** [comment]
What if we make the system runnable locally before improving in blind?

**Comment by MeikelLP** [comment]
If you can help me with that I would appreciate it.

**Comment by MeikelLP** [comment]
Additionally I extracted the css to be in an individual file (improved caching).
Fixed theme not applying when not logged in (theme component always visible)
Fixed some minor issues with css selector: `html html` (see `_fixes.sass`)
Fixed some changes in bulma 0.74 -> 0.75 (probably)

**Comment by sizovs** [comment]
This one breaks everything and contains quite a few changes to review in

**Pull request closed without merging**
